config/routes.rb
require 'dynamic_router'
Rails.application.routes.draw do
  # FIXME: routes always on spanish, redirect the legacy (english) routes

  get '', to: redirect("/#{I18n.locale}")

  # redsys MerchantURL 
  post '/orders/callback/redsys', to: 'orders#callback_redsys', as: 'orders_callback_redsys'

  namespace :api do
    scope :v1 do 
      scope :gcm do 
        post 'registrars', to: 'v1#gcm_registrate'
        delete 'registrars/:registrar_id', to: 'v1#gcm_unregister'
      end
      scope :user do
        get 'exists', to: 'v1#user_exists'
      end
    end
  end

  get '/favicon.ico', to: "organization#favicon"

  scope "/(:locale)", locale: /es|ca|eu/ do 

    devise_for :users, controllers: { 
      registrations: 'registrations', 
      passwords:     'passwords', 
      confirmations: 'confirmations'
    } 

    get '/privacy-policy', to: 'page#privacy_policy', as: 'page_privacy_policy'
    get '/preguntas-frecuentes', to: 'page#faq', as: 'faq'

    if Rails.application.secrets.features["notifications"]
      get :notices, to: 'notice#index', as: 'notices'
    end

    if Rails.application.secrets.features["openid"]
      get '/openid/discover', to: 'open_id#discover', as: "open_id_discover"
      get '/openid', to: 'open_id#index', as: "open_id_index"
      post '/openid', to: 'open_id#create', as: "open_id_create"
      get '/user/:id', to: 'open_id#user', as: "open_id_user"
      get '/user/xrds', to: 'open_id#xrds', as: "open_id_xrds"
    end

    if Rails.application.secrets.features["participation_teams"]
      get '/equipos-de-accion-participativa', to: 'participation_teams#index', as: 'participation_teams'
      put '/equipos-de-accion-participativa/entrar(/:team_id)', to: 'participation_teams#join', as: 'participation_teams_join'
      put '/equipos-de-accion-participativa/dejar(/:team_id)', to: 'participation_teams#leave', as: 'participation_teams_leave'
      patch '/equipos-de-accion-participativa/actualizar', to: 'participation_teams#update_user', as: 'participation_teams_update_user'
    end

    if Rails.application.secrets.features["proposals"]
      get '/propuestas', to: 'proposals#index', as: 'proposals'
      get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
      get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
      post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'
    end

    if Rails.application.secrets.features["elections"]
      get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
      get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
      get '/vote/check/:election_id', to: 'vote#check', as: :check_vote
    end

    if Rails.application.secrets.features["verification_presencial"]
      scope '/verificadores' do 
        get '/', to: 'verification#step1', as: :verification_step1
        get '/nueva', to: 'verification#step2', as: :verification_step2
        get '/confirmar', to: 'verification#step3', as: :verification_step3
        post '/search', to: 'verification#search', as: :verification_search
        post '/confirm', to: 'verification#confirm', as: :verification_confirm
        get '/ok', to: 'verification#result_ok', as: :verification_result_ok
        get '/ko', to: 'verification#result_ko', as: :verification_result_ko
      end
      scope '/verificaciones' do 
        get '/', to: 'verification#show', as: :verification_show
      end
    end
    
    if Rails.application.secrets.features["microcredits"]
      get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
      get '/microcréditos', to: redirect('/microcreditos')
      get '/microcreditos/provincias', to: 'microcredit#provinces'
      get '/microcreditos/municipios', to: 'microcredit#towns'
      get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
      get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
      get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
      post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    end
    
    authenticate :user do

      if Rails.application.secrets.features["verification_sms"]
        scope :validator do
          scope :sms do 
            get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
            get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
            get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
            post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
            post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
            post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
          end
        end
      end
      
      if Rails.application.secrets.features["collaborations"]
        scope :colabora do
          delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
          get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
          get '', to: 'collaborations#new', as: 'new_collaboration'
          get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
          post 'crear', to: 'collaborations#create', as: 'create_collaboration'
          post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
          get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
          get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
        end
      end

      if Rails.application.secrets.features["blog"]
        scope :brujula do
          get '', to: 'blog#index', as: 'blog'
          get ':id', to: 'blog#post', as: 'post'
          get 'categoria/:id', to: 'blog#category', as: 'category'
        end
      end
    end

    # http://stackoverflow.com/a/8884605/319241 
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root 'tools#index', as: :authenticated_root
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root 'devise/sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do
    mount Resque::Server.new, at: '/admin/resque', as: :resque
  end

  load "./vendor/overrides/#{Rails.application.secrets.organization["folder"]}/config/routes.rb"

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :authenticate_user! 
  before_action :user_elections

  def index
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def user_elections
    @all_elections = Election.upcoming_finished.map { |e| e if e.has_valid_location_for? current_user } .compact

    @elections = @all_elections.select { |e| e.is_active? }
    @upcoming_elections = @all_elections.select { |e| e.is_upcoming? }
    @finished_elections = @all_elections.select { |e| e.recently_finished? }
  end
end

app/views/tools/_demo.html.erb
<% content_for :title, "Forma parte del cambio en Andalucía" %>

<section class="tools">
<%= link_to image_tag("banner_collabs.png", alt: "colabora.podemos.info", style: 'max-width:100%'), new_collaboration_path %>
</section>

<%= content_tag(:h2, "Forma parte del cambio en Andalucía") %>
<section class="tools">
<ul>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte viaje a Sevilla</h3>
    <div class="tool-text">
      <p>Si vas en coche a Sevilla y te sobran plazas, anúncialo y otras personas podrán ponerse en contacto contigo para compartir el viaje y los gastos del mismo. </p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu coche", share_car_sevilla_path, class: "button" %>
      <%= link_to "Encuentra coche", find_car_sevilla_path, class: "button" %>
    </div>
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte viaje a Dos Hermanas</h3>
    <div class="tool-text">
      <p>Si vas en coche a Dos Hermanas y te sobran plazas, anúncialo y otras personas podrán ponerse en contacto contigo para compartir el viaje y los gastos del mismo. </p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu coche", share_car_doshermanas_path, class: "button" %>
      <%= link_to "Encuentra coche", find_car_doshermanas_path, class: "button" %>
    </div>
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>Comparte casa</h3>
    <div class="tool-text">
      <p>Si tienes sitio en tu casa en Sevilla, compártelo y haz posible que otras personas puedan participar en el cambio en Andalucía.</p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <%= link_to "Comparte tu casa", offer_hospitality_path, class: "button" %>
      <%= link_to "Encuentra alojamiento", find_hospitality_path, class: "button" %>
    </div><!--.buttonbox-->
  </div><!--.box-tool-->
  </li>
  <li class="box-tool">
  <div class="box-tool">
    <h3>La expresión del cambio en Andalucía</h3>
    <div class="tool-text">
      <p>Comparte tus creaciones por el cambio en Andalucía. También puedes participar en el concurso de carteles para el 20M.</p>
    </div><!--.tool-text-->
    <div class="buttonbox">
      <a href="https://laexpresiondelcambio.info" class="button">COMPARTE TUS CREACIONES</a>
    </div><!--.buttonbox-->
  </div><!--.box-tool-->
  </li>
</ul>
</section>

app/views/tools/_election.html.erb
<p class="sub-h3">
<% if current_user.can_change_vote_location? and election.multiple_territories?%>
Accederás a la votación de<% case election.scope
     when 1 %> la comunidad autónoma en la
  <% when 2 %> la provincia en la
  <% when 3 %>l municipio en el 
  <% when 4 %> la isla en la
  <% end %> que estás inscrito/a. Puedes actualizarlo pero recuerda que solo tu último voto es válido.<% end %>
<div class="box-poll">
  <div>
    <p class="poll-q"><%= election.full_title_for current_user %></p>
    <p class="date"><%= l election.starts_at, format: :short %> - <%= l election.ends_at, format: :short %></p>
  </div>
  <% if election.has_valid_location_for? current_user %>
    <%= link_to create_vote_path(election_id: election.id), class: 'button button-vote' do %>
      <span>Votar</span>
    <% end %>
  <% end %>
</div>

app/views/tools/_election_finished.html.erb
<% content_for :title, "Herramientas de participación ciudadana" %>
<%= content_tag(:h2, "Herramientas de participación ciudadana") %>
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> ya han cerrado.</strong></h3>
    <p class="sub-h3"> <%= raw election.close_message %></p>
  </div>
</div>

app/views/tools/_election_upcoming.html.erb
<% content_for :title, "Herramientas de participación ciudadana" %>
<%= content_tag(:h2, "Herramientas de participación ciudadana") %>
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> están a punto de empezar.</strong></h3>
    <p class="sub-h3">Las urnas se abrirán el <%= l election.starts_at, format: "%-d de %B de %Y a las %H:%M" %>.</p>
  </div>
</div>

app/views/tools/_election_wrapper.html.erb
<% if elections.count > 0 %>
  <%= render partial: 'elections' %>
<% else %>
  <% if upcoming_elections.count > 0 %>
    <%= render partial: 'election_upcoming', locals: { election: upcoming_elections[-1] } %>
  <% elsif finished_elections.count > 0 %>
    <%= render partial: 'election_finished', locals: { election: finished_elections[-1] } %>
  <% else %>
    <%= render partial: "other_tools" %>
  <% end %>
<% end %>

app/views/tools/_elections.html.erb
<% content_for :title, "Herramientas de participación ciudadana" %>
<%= content_tag(:h2, "Herramientas de participación ciudadana") %>
<div class="box">
  <div class="box-vote">
    <% if !current_user.has_vote_town? %>
      <p><strong>Por favor, indica tu lugar de participación en tu perfil.</strong></p>
    <% end %>
    <h3><strong>Hay <% if @elections.length==1%>una votación<%else%>votaciones<%end%> en curso. ¡Participa!</strong></h3>
    <p class="sub-h3"><% if @elections.length==1%>La votación utiliza<%else%>Las votaciones utilizan<%end%> el sistema seguro de <a href="https://agoravoting.com" target="_blank"><b>Agora Voting</b></a>.</p>
    <% @elections.each do |election| %>
      <%= render partial: "election", locals: { election: election } %>
    <% end %>
  </div>
</div>

app/views/tools/_last_election.html.erb
<div class="box">
  <div class="box-vote">
    <h3><strong>Las votaciones de <%= election.title %> ya han cerrado.</strong></h3>
    <p class="sub-h3"> <%= raw election.close_message %></p>
  </div>
</div>

app/views/tools/_other_tools.html.erb
<% content_for :title, "Herramientas de participación ciudadana" %>
<%= content_tag(:h2, "Herramientas de participación ciudadana") %>
<section class="tools">
  <ul>
    <li class="box-tool-large">
      <div class="box-tool-large">
        <h3>Iniciativas ciudadanas</h3>        
        <div class="tool-text">
            <p>Iniciativas Ciudadanas Podemos</p>
        </div><!--.tool-text-->

        <div class="buttonbox">
            <%= link_to "Ver iniciativas", proposals_path, class: "button" %>
        </div>
      </div><!--.box-tool-->
    </li>
    <li class="box-tool">
      <div class="box-tool">
        <h3>Plaza Podemos</h3>
        <div class="tool-text">
            <p>El lugar oficial de encuentro y debate de Podemos: comparte materiales, opiniones, ideas, proyectos todo y mucho más.</p>
        </div><!--.tool-text-->

        <div class="buttonbox">
            <%= link_to "Ir a Plaza Podemos", "http://reddit.com/r/podemos", class: "button", target: "_blank" %>
        </div>
      </div><!--.box-tool-->
    </li>
    <li class="box-tool">
      <div class="box-tool">
        <h3>AppGree</h3>        
        <div class="tool-text">
            <p>La aplicación para opinar y proponer en tiempo real.</p>
        </div><!--.tool-text-->
        
        <div class="buttonbox">
            <%= link_to "Descargar APP", "http://www.appgree.com/descarga-appgree/", class: "button", target: "_blank" %>
        </div><!--.buttonbox-->
      </div><!--.box-tool-->
    </li>
    <li class="box-tool">
      <div class="box-tool">
        <h3>Equipos de Acción Participativa</h3>
        <div class="tool-text">
            <p>Nuestra intención es crear cientos de estos equipos, con el objetivo de dinamizar la participación y reforzar la movilización en los municipios.</p>
        </div><!--.tool-text-->        
        <div class="buttonbox">
            <%= link_to "Leer más", participation_teams_path, class: "button" %>
            <%= render partial: "participation_teams/wants_participation_buttons" %>
        </div><!--.buttonbox-->
      </div><!--.box-tool-->
    </li>
  </ul>
</section><!--.tools-->

app/views/tools/_verification_pending.html.erb
<div class="col-b-4a12">
  <div class="verif-new-first">
    <p class="title"><%= t('verification.pending0_html') %></p>
    <p><%= t('verification.pending1_html') %></p>

    <div class="verif-new-docu">
      <span><%= image_tag "ico.verif.dni.png" %></span>
      <span class="verif-docu-txt"><%= t('verification.pending2_html') %></span>
    </div>
  </div>
</div>

<div class="col-b-4a12">
  <div class="verif-new-second">
    <p class="title"><%= t('verification.pending3_html') %></p>

    <div class="verif-left">
      <span class="verif-item verif-img-1"><%= image_tag "ico.verif.passport.png" %></span>
      <ul class="verif-item">
        <%= t('verification.pending4_html') %>
      </ul>
    </div>

    <span class="verif-new-or">
        <%= t('verification.pending5_html') %>
    </span>

    <div class="verif-right">
      <ul class="verif-item">
        <%= t('verification.pending6_html') %>
      </ul>
      <span class="verif-item verif-img-2"><%= image_tag "ico.verif.doc.png" %></span>
    </div>

    </div>
  </div>
</div>

<div class="verif-new-third">
  <p class="title"> <%= t('verification.pending7_html') %> </p>
  <%= render partial: "verification/map" %>
</div>

app/views/tools/index.html.erb
<div class="content-content cols">
  <div class="row">
    <div class="col-b-4a12">
      <% if @elections.count > 0 %>
        <%= render partial: 'elections' %>
      <% else %>
        <% if @upcoming_elections.count > 0 %>
          <%= render partial: 'election_upcoming', locals: { election: @upcoming_elections[-1] } %>
        <% elsif @finished_elections.count > 0 %>
          <%= render partial: 'election_finished', locals: { election: @finished_elections[-1] } %>
        <% elsif Rails.env.development? %>
          <%= render partial: "other_tools" %>
        <% elsif Date.today < Date.civil(2015,03,20) %>
          <%= render partial: 'demo' %>
        <% else %>
          <%= render partial: "other_tools" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>