config/routes.rb
require 'dynamic_router'
Rails.application.routes.draw do
  # FIXME: routes always on spanish, redirect the legacy (english) routes

  get '', to: redirect("/#{I18n.locale}")

  # redsys MerchantURL 
  post '/orders/callback/redsys', to: 'orders#callback_redsys', as: 'orders_callback_redsys'

  namespace :api do
    scope :v1 do 
      scope :gcm do 
        post 'registrars', to: 'v1#gcm_registrate'
        delete 'registrars/:registrar_id', to: 'v1#gcm_unregister'
      end
      scope :user do
        get 'exists', to: 'v1#user_exists'
      end
    end
  end

  get '/favicon.ico', to: "organization#favicon"

  scope "/(:locale)", locale: /es|ca|eu/ do 

    devise_for :users, controllers: { 
      registrations: 'registrations', 
      passwords:     'passwords', 
      confirmations: 'confirmations'
    } 

    get '/privacy-policy', to: 'page#privacy_policy', as: 'page_privacy_policy'
    get '/preguntas-frecuentes', to: 'page#faq', as: 'faq'

    if Rails.application.secrets.features["notifications"]
      get :notices, to: 'notice#index', as: 'notices'
    end

    if Rails.application.secrets.features["openid"]
      get '/openid/discover', to: 'open_id#discover', as: "open_id_discover"
      get '/openid', to: 'open_id#index', as: "open_id_index"
      post '/openid', to: 'open_id#create', as: "open_id_create"
      get '/user/:id', to: 'open_id#user', as: "open_id_user"
      get '/user/xrds', to: 'open_id#xrds', as: "open_id_xrds"
    end

    if Rails.application.secrets.features["participation_teams"]
      get '/equipos-de-accion-participativa', to: 'participation_teams#index', as: 'participation_teams'
      put '/equipos-de-accion-participativa/entrar(/:team_id)', to: 'participation_teams#join', as: 'participation_teams_join'
      put '/equipos-de-accion-participativa/dejar(/:team_id)', to: 'participation_teams#leave', as: 'participation_teams_leave'
      patch '/equipos-de-accion-participativa/actualizar', to: 'participation_teams#update_user', as: 'participation_teams_update_user'
    end

    if Rails.application.secrets.features["proposals"]
      get '/propuestas', to: 'proposals#index', as: 'proposals'
      get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
      get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
      post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'
    end

    if Rails.application.secrets.features["elections"]
      get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
      get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
      get '/vote/check/:election_id', to: 'vote#check', as: :check_vote
    end

    if Rails.application.secrets.features["verification_presencial"]
      scope '/verificadores' do 
        get '/', to: 'verification#step1', as: :verification_step1
        get '/nueva', to: 'verification#step2', as: :verification_step2
        get '/confirmar', to: 'verification#step3', as: :verification_step3
        post '/search', to: 'verification#search', as: :verification_search
        post '/confirm', to: 'verification#confirm', as: :verification_confirm
        get '/ok', to: 'verification#result_ok', as: :verification_result_ok
        get '/ko', to: 'verification#result_ko', as: :verification_result_ko
      end
      scope '/verificaciones' do 
        get '/', to: 'verification#show', as: :verification_show
      end
    end
    
    if Rails.application.secrets.features["microcredits"]
      get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
      get '/microcréditos', to: redirect('/microcreditos')
      get '/microcreditos/provincias', to: 'microcredit#provinces'
      get '/microcreditos/municipios', to: 'microcredit#towns'
      get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
      get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
      get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
      post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    end
    
    authenticate :user do

      if Rails.application.secrets.features["verification_sms"]
        scope :validator do
          scope :sms do 
            get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
            get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
            get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
            post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
            post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
            post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
          end
        end
      end
      
      if Rails.application.secrets.features["collaborations"]
        scope :colabora do
          delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
          get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
          get '', to: 'collaborations#new', as: 'new_collaboration'
          get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
          post 'crear', to: 'collaborations#create', as: 'create_collaboration'
          post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
          get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
          get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
        end
      end

      if Rails.application.secrets.features["blog"]
        scope :brujula do
          get '', to: 'blog#index', as: 'blog'
          get ':id', to: 'blog#post', as: 'post'
          get 'categoria/:id', to: 'blog#category', as: 'category'
        end
      end
    end

    # http://stackoverflow.com/a/8884605/319241 
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root 'tools#index', as: :authenticated_root
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root 'devise/sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do
    mount Resque::Server.new, at: '/admin/resque', as: :resque
  end

  load "./vendor/overrides/#{Rails.application.secrets.organization["folder"]}/config/routes.rb"

end

app/models/microcredit.rb
class Microcredit < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  acts_as_paranoid
  has_many :loans, class_name: "MicrocreditLoan"

  # example: "100€: 100\r500€: 22\r1000€: 10"
  validates :limits, format: { with: /\A(\D*\d+\D*\d+\D*)+\z/, message: "Introduce pares (monto, cantidad)"}
  validate :check_limits_with_phase

  scope :active, -> {where("? between starts_at and ends_at", DateTime.now)}
  scope :upcoming_finished, -> { where("ends_at > ? AND starts_at < ?", 7.days.ago, 1.day.from_now).order(:title)}

  def is_active?
    ( self.starts_at .. self.ends_at ).cover? DateTime.now
  end

  def is_upcoming?
    self.starts_at > DateTime.now and self.starts_at < 1.day.from_now
  end

  def recently_finished?
    self.ends_at > 7.days.ago and self.ends_at < DateTime.now 
  end

  def limits
    @limits ||= parse_limits self[:limits]
  end

  def limits=(l)
    self[:limits] = l
    @limits = parse_limits self[:limits]
  end

  def single_limit
    @limits
  end
  
  def method_missing(name, *args, &blk)
    if name.to_s.start_with? "single_limit_"
      amount = name[13..-1].to_i
      if @limits.include? amount
        @limits[amount]
      end
    else
      super
    end
  end

  def parse_limits limits_string
    Hash[* limits_string.scan(/\d+/).map {|x| x.to_i} ] if limits_string
  end

  def campaign_status
    # field IS NOT NULL returns integer on SQLite and boolean in postgres, so both values are checked and converted to boolean
    @campaign_status ||= loans.group(:amount, "confirmed_at IS NOT NULL", "counted_at IS NOT NULL", "discarded_at IS NOT NULL").pluck(:amount, "confirmed_at IS NOT NULL", "counted_at IS NOT NULL", "discarded_at IS NOT NULL", "COUNT(*)").sort_by(&:first).map {|x| [x[0], (x[1]==true||x[1]==1), (x[2]==true||x[2]==1), (x[3]==true||x[3]==1), x[4]] }
  end

  def phase_status
    # field IS NOT NULL returns integer on SQLite and boolean in postgres, so both values are checked and converted to boolean
    @phase_status ||= loans.phase.group(:amount, "confirmed_at IS NOT NULL", "counted_at IS NOT NULL", "discarded_at IS NOT NULL").pluck(:amount, "confirmed_at IS NOT NULL", "counted_at IS NOT NULL", "discarded_at IS NOT NULL", "COUNT(*)").sort_by(&:first).map {|x| [x[0], (x[1]==true||x[1]==1), (x[2]==true||x[2]==1), (x[3]==true||x[3]==1), x[4]] }
  end

  def remaining_percent
    time = 1-[ [(DateTime.now.to_f-starts_at.to_f) / (ends_at.to_f-starts_at.to_f), 0.0].max, 1.0].min
    progress = 1-[ [1.0*self.campaign_counted_amount / self.total_goal, 0.0].max, 1.0].min
    progress*time
  end

  def current_percent amount, add
    remaining = self.remaining_percent
    current = campaign_status.collect {|x| x[4]*(x[1] ? remaining*remaining : 1.0) if x[0]==amount and (not x[3] or x[2])} .compact.sum + add
    current_counted = campaign_status.collect {|x| x[4]*(x[1] ? remaining*remaining : 1.0) if x[0]==amount and x[2]} .compact.sum
    current == 0 ? 0 : (current_counted+add)/current
  end

  def has_amount_available? amount
    current = phase_status.collect {|x| x[4] if x[0]==amount and x[2] } .compact.sum
    limits[amount] and limits[amount] > current
  end

  def should_count? amount, confirmed
    # check that there is any remaining loan for this amount and phase
    remaining = phase_remaining(amount)
    return false if (remaining and remaining.first.last<=0)
    
    if confirmed
      return true
    else
      percent = self.remaining_percent
      (current_percent(amount, 1)-percent).abs<(current_percent(amount, 0)-percent).abs
    end
  end

  def phase_current_for_amount amount
    phase_status.collect {|x| x[4] if x[0]==amount and x[2]} .compact.sum
  end

  def phase_remaining filter_amount=nil
    limits.map do |amount, limit|
      [amount, [0, limit-phase_status.collect {|x| x[4] if x[0]==amount and x[2]} .compact.sum].max ] if filter_amount.nil? or filter_amount==amount
    end .compact
  end

  def phase_limit_amount
    limits.map do |k,v| k*v end .sum
  end

  def check_limits_with_phase
    if self.limits.any? { |amount, limit| limit < self.phase_current_for_amount(amount) }
      self.errors.add(:limits, "No puedes establecer un limite para un monto por debajo de los microcréditos visibles en la web con ese monto en la fase actual.")
    end
  end

  def phase_counted_amount
    phase_status.collect {|x| x[0]*x[4] if x[2] } .compact.sum
  end

  def campaign_created_amount
    campaign_status.collect {|x| x[0]*x[4] } .compact.sum
  end

  def campaign_unconfirmed_amount
    campaign_status.collect {|x| x[0]*x[4] if not x[1] } .compact.sum
  end

  def campaign_confirmed_amount
    campaign_status.collect {|x| x[0]*x[4] if x[1] } .compact.sum
  end

  def campaign_not_counted_amount
    campaign_status.collect {|x| x[0]*x[4] if not x[2] } .compact.sum
  end

  def campaign_counted_amount
    campaign_status.collect {|x| x[0]*x[4] if x[2] } .compact.sum
  end

  def campaign_discarded_amount
    campaign_status.collect {|x| x[0]*x[4] if x[3] } .compact.sum
  end

  def campaign_created_count
    campaign_status.collect {|x| x[4] } .compact.sum
  end

  def campaign_unconfirmed_count
    campaign_status.collect {|x| x[4] if not x[1] } .compact.sum
  end

  def campaign_confirmed_count
    campaign_status.collect {|x| x[4] if x[1] } .compact.sum
  end

  def campaign_not_counted_count
    campaign_status.collect {|x| x[4] if not x[2] } .compact.sum
  end

  def campaign_counted_count
    campaign_status.collect {|x| x[4] if x[2] } .compact.sum
  end

  def campaign_discarded_count
    campaign_status.collect {|x| x[4] if x[3] } .compact.sum
  end

  def completed
    self.campaign_confirmed_amount>=self.total_goal
  end

  def change_phase!
    if self.update_attribute(:reset_at, DateTime.now)
      @phase_status = nil # resets phase status
      self.loans.where.not(confirmed_at:nil).where(counted_at:nil).each do |loan|
        loan.update_counted_at
      end
    end
  end

  def slug_candidates
    [
      :title,
      [:title, DateTime.now.year],
      [:title, DateTime.now.year, DateTime.now.month],
      [:title, DateTime.now.year, DateTime.now.month, DateTime.now.day]
    ]
  end

  def self.total_current_amount
    Microcredit.upcoming_finished.sum(:total_goal)
  end

  def subgoals
    @subgoals ||= YAML.load(self[:subgoals]) if self[:subgoals]
  end
end

app/controllers/microcredit_controller.rb
class MicrocreditController < ApplicationController

  def provinces
    render partial: 'subregion_select', locals:{ country: (params[:microcredit_loan_country] or "ES"), province: params[:microcredit_loan_province], disabled: false, required: true, title:"Provincia"}
  end

  def towns
    render partial: 'municipies_select', locals:{ country: (params[:microcredit_loan_country] or "ES"), province: params[:microcredit_loan_province], town: params[:microcredit_loan_town], disabled: false, required: true, title:"Municipio"}
  end

  def index
    @all_microcredits = Microcredit.upcoming_finished

    @microcredits = @all_microcredits.select { |m| m.is_active? }

    if @microcredits.length == 0
      @upcoming_microcredits = @all_microcredits.select { |m| m.is_upcoming? } .sort_by(&:starts_at)
      @finished_microcredits = @all_microcredits.select { |m| m.recently_finished? } .sort_by(&:ends_at).reverse
    end
  end

  def login
    authenticate_user!
    redirect_to new_microcredit_loan_path(params[:id])
  end

  def new_loan
    @microcredit = Microcredit.find(params[:id])
    redirect_to microcredit_path unless @microcredit and @microcredit.is_active?

    @loan = MicrocreditLoan.new
    @user_loans = current_user ? @microcredit.loans.where(user:current_user) : []
  end

  def create_loan
    @microcredit = Microcredit.find(params[:id])
    redirect_to microcredit_path unless @microcredit and @microcredit.is_active?
    @user_loans = current_user ? @microcredit.loans.where(user:current_user) : []

    @loan = MicrocreditLoan.new(loan_params) do |loan|
      loan.microcredit = @microcredit
      loan.user = current_user if current_user
      loan.ip = request.remote_ip
    end

    if not current_user
      @loan.set_user_data loan_params
    end 

    @loan.transaction do
      if (current_user or verify_recaptcha) and @loan.save
        @loan.update_counted_at
        UsersMailer.microcredit_email(@microcredit, @loan).deliver
        redirect_to microcredit_path, notice: 'En unos segundos recibirás un correo electrónico con toda la información necesaria para finalizar el proceso de suscripción del microcrédito Podemos. Por favor, ten en cuenta que es posible que el contador no se actualice de forma inmediata. ¡Gracias por colaborar!<br/>Si quieres ayudarnos a difundir esta campaña, <a href="http://twitter.com/home/?status=Acabo%20de%20suscribir%20un%20microcr%C3%A9dito%20Podemos%20para%20financiar%20la%20campa%C3%B1a%20electoral.%20Puedes%20invertir%20en%20el%20cambio%20en%20microcreditos.podemos.info">compártelo en Twitter</a>.'
      else
        flash.now[:error] = @microcredit.errors.full_messages
        render :new_loan
      end
    end
  end

  private

  def loan_params
    if current_user
      params.require(:microcredit_loan).permit(:amount, :terms_of_service, :minimal_year_old)
    else
      params.require(:microcredit_loan).permit(:first_name, :last_name, :document_vatid, :email, :address, :postal_code, :town, :province, :country, :amount, :terms_of_service, :minimal_year_old)
    end
  end
end

app/helpers/microcredit_helper.rb
module MicrocreditHelper
end

app/views/microcredit/index.html.erb
<% content_for :title, "Microcréditos" %>
<div class="content-content">
<h2>Microcréditos Podemos</h2>
<p>Ayúdanos a financiar las campañas electorales suscribiendo un microcrédito Podemos. Cuando nos ingresen la subvención electoral te devolveremos la cantidad aportada. <%= link_to "Más informacion", microcredits_info_path %></p>

<% if @microcredits.length==0 %>
  <% if @upcoming_microcredits.count > 0 %>
    <h3>Las próxima campaña de microcréditos comenzará en unos momentos</h3>
    <p>Podrás suscribir un microcrédito Podemos a partir de las <%= @upcoming_microcredits.first.starts_at.strftime "%H:%M"%> del día <%= @upcoming_microcredits.first.starts_at.strftime "%d/%m"%>.</p>
  <% elsif @finished_microcredits.count > 0 %>
    <h3>La campaña de microcréditos ha acabado</h3>
    <p>Hemos recaudado en total <%= number_to_euro(@finished_microcredits.map {|m| m.campaign_confirmed_amount*100 } .sum, 0) %>. ¡Muchas gracias a todos por colaborar con el cambio!</p>
  <% else %>
    <h3>En este momento no hay campañas de microcréditos activas.</h3>
    <p>No te preocupes, te avisaremos cuando abramos la próxima campaña.</p>
  <% end %>
<% else %>
  <div class="microcredit_boxes">
    <% @microcredits.each do |m| %>
    <section class="<%= m.completed ? 'completed' : 'active' %>">
    <div>
      <h2><%=m.title%></h2>
      <% if m.completed %>
      <%= fa_icon "check-circle" %>
      <div class="info">
        <p><strong>Objetivo alcanzado</strong></p>
        <p>Hemos recaudado <%=number_to_euro m.campaign_confirmed_amount*100, 0%>.</p>
        <p>¡Muchas gracias por colaborar con el cambio!</p>
      </div>
      <% else %>
      <div class="js-mc-graph">
        <div></div>
        <canvas width="90" heigth="100"></canvas>
        <div alt="<%=m.phase_counted_amount%>€" class="hide js-mc-total"><%= m.phase_counted_amount %>€</div>
        <div alt="Restante" class="hide js-mc-pending"><%= m.phase_limit_amount-m.phase_counted_amount %>€</div>
      </div>
      <div class="info">
        <p><strong>Fase actual:</strong><br/><%=number_to_euro m.phase_counted_amount*100, 0%> / <%= number_to_euro m.phase_limit_amount*100, 0%><br/><strong>Acumulado:</strong> <%= number_to_euro m.campaign_counted_amount*100, 0%></p><% 
            if m.subgoals
              remaining = m.campaign_counted_amount || 0 %><ul class='subgoals'><% 
              m.subgoals.each do |concept,subgoal| %><li><%=concept%>:&nbsp;<%=number_to_euro (remaining>subgoal ? subgoal : remaining)*100, 0%></li><%                 
                remaining -= subgoal
                if remaining <= 0 then break end
              end %></ul><% 
            end %><div class="buttonbox"><%= link_to "Quiero colaborar", new_microcredit_loan_path(m), class: 'button' %></div>
      </div>
      <% end %>
    </div>
    </section>
    <% end %>
  </div>
<% end %>
</div>

app/views/microcredit/new_loan.html.erb
<% content_for :title, "Microcréditos" %>


<div class="content-content microcredits-wrapper<%= " completed" if @microcredit.completed%>">
<% if !current_user %>
  <div class="modal-dialog">
    <div>    
      <h2>Microcréditos Podemos - <%=@microcredit.title%></h2>
      <p>Te recomendamos que <%= link_to "accedas con tu usuario del Portal de Participación", microcredit_login_path%> para que no tengas que rellenar nuevamente estos datos y para que puedas consultar el estado del préstamo en el futuro.</p>
      <div class="buttonbox"><a class="close button">Continuar sin identificarse</a>&nbsp;&nbsp; &nbsp;&nbsp;<%= link_to "Acceder con tu usuario", microcredit_login_path, class:"button"%></div>
    </div>
  </div>
<% end %>

<h2>Microcréditos Podemos - <%=@microcredit.title%></h2>
<p>Ayúdanos a financiar las campañas electorales suscribiendo un microcrédito Podemos. Cuando nos ingresen la subvención electoral te devolveremos la cantidad aportada. <%= link_to "Más informacion", microcredits_info_path %></p>

<% if @microcredit.completed %>
  <div>
    <%=fa_icon "check-circle"%>
    <div class="microcredit-ended">
      <h3>La campaña de microcréditos ha finalizado</h3>
      <p>Hemos recaudado <%= number_to_euro(@microcredit.campaign_confirmed_amount*100, 0) %>. ¡Muchas gracias a todos por colaborar con el cambio!</p>
    </div>
  </div>
<% else %>
  <% if @microcredit.contact_phone and not @microcredit.contact_phone.empty?%>
  <p><%=fa_icon "phone-square"%> Si necesitas ayuda contacta al <strong><%=@microcredit.contact_phone%></strong>.</p>
  <% end %>
  <%= errors_in_form @loan %>
  <%= semantic_form_for @loan, url: create_microcredit_loan_path, html: {method: :post, autocomplete: 'off'} do |f| %>

    <% if  current_user %>
      <% if @user_loans.length > 0 %>
        <%= alert_box "Información" do %>
          <% if @user_loans.length == 1 %>
          <p>Ya has suscrito un microcrédito para esta campaña por un importe de <%= number_to_euro @user_loans.map { |l| l.amount*100 } .sum%>.</p>
          <% else %>
          <p>Ya has suscrito <%=@user_loans.length%> microcréditos para esta campaña por un importe total de <%= number_to_euro @user_loans.map { |l| l.amount*100 } .sum%>.</p>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <fieldset>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:first_name) %>
            <%= field_notice_box %>
          <% end %>
          <%= f.input :first_name, required: true, input_html: {autofocus: true, required: true, class: 'input-xl'} %>
        </div>

        <div class="inputlabel-box">
          <% if @loan.errors.include?(:last_name) %>
              <%= field_notice_box %>
          <% end %>
          <%= f.input :last_name, required: true, input_html: {required: true, class: 'input-xl'} %>
        </div>

        <div class="inputlabel-box">
          <% if @loan.errors.include?(:document_vatid) %>
              <%= field_notice_box %>
          <% end %>
          <%= f.input :document_vatid,
                      required: true %>
        </div>

        <div class="inputlabel-box">
          <% if @loan.errors.include?(:email) %>
              <%= field_notice_box %>
          <% end %>
          <%= f.input :email,
                      required: true %>
        </div>
      </fieldset>
      <fieldset>
        <legend><span>Domicilio</span></legend>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:country) %>
              <%= field_notice_box %>
          <% end %>
          <%= label @loan, :country, class: "control-label", required: :required do %>
            País
            <abbr title="requerido">*</abbr>
          <% end %>
          <%= select_tag "microcredit_loan[country]", options_from_collection_for_select(get_countries, "code", "name", @loan.country), { disabled: false, required: true, data: { allowClear: true } } %>
        </div>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:province) %>
              <%= field_notice_box %>
          <% end %>
          <%= render partial: 'subregion_select', locals:{ country: @loan.country, province: @loan.province, disabled: false, required: true, title:"Provincia" } %>
        </div>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:town) %>
              <%= field_notice_box %>
          <% end %>
          <%= render partial: 'municipies_select', locals: { country: @loan.country, province: @loan.province, town:  @loan.town, disabled: false, required: true, title: "Municipio" } %>
        </div>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:postal_code) %>
              <%= field_notice_box %>
          <% end %>
          <%= f.input :postal_code, required: true, input_html: {required: true, class: 'input-s'} %>
        </div>
        <div class="inputlabel-box">
          <% if @loan.errors.include?(:address) %>
              <%= field_notice_box %>
          <% end %>
          <%= f.input :address, required: true, input_html: {required: true, class: 'input-xl'} %>
        </div>
      </fieldset>
    <% end %>
    <fieldset class="with-tos">
      <div>
        <% if @loan.errors.include?(:amount) %>
            <%= field_notice_box %>
        <% end %>
          <%= label @loan, :amount, class: "control-label", required: :required do %>
            Importe
            <abbr title="requerido">*</abbr>
          <% end %>
        <div class="radio_options">
          <% @microcredit.phase_remaining.each do |amount,remaining| %> 
          <input id="microcredit_loan_amount_<%=amount%>" name="microcredit_loan[amount]" value="<%=amount%>" type="radio"<%=" checked" if amount==@loan.amount%><%=' disabled class=disabled' if remaining==0%> />
          <div><%=fa_icon "#{remaining==0 ? "times" : "check"}-circle", text: "#{number_to_euro amount*100,0}"%><span>(quedan <%=remaining%>)</span></div>
          <% end %>
        </div>
      </div>
    <% if not current_user %>
      <div class="inputlabel-box">
        <%= f.label :captcha %>
        <div class="input-box">
          <%= recaptcha_tags %>
        </div>
      </div>
    <% end %>

      <div class="inputlabel-box">
        <% if @loan.errors.include?(:minimal_year_old) %>
            <%= field_notice_box %>
        <% end %>
        <div class="input-box">
          <%= f.check_box :minimal_year_old, class: 'checkbox' %>
          <%= f.label :minimal_year_old, class: 'text-xl' do %>
            Declaro ser mayor de 18 años.
          <% end %>
        </div>
      </div>

      <div class="inputlabel-box">
        <% if @loan.errors.include?(:terms_of_service) %>
            <%= field_notice_box %>
        <% end %>
        <div class="input-box">
          <%= f.check_box :terms_of_service, class: 'checkbox' %>
          <%= f.label :terms_of_service, class: 'text-xl' do %>
            Acepto las condiciones generales del Contrato civil de suscripción de microcréditos de Podemos. <a href="<%=@microcredit.agreement_link%>" target="_blank">Contrato civil de suscripción de microcréditos de Podemos</a>
          <% end %>
        </div>
      </div>
    </fieldset>
    <%= f.actions class: 'enter' do %>
      <%= f.action :submit, :as => :input, button_html: {class: 'button'} %>
    <% end %>
  <% end %>
<% end %>
</div>