config/routes.rb
require 'dynamic_router'
Rails.application.routes.draw do
  # FIXME: routes always on spanish, redirect the legacy (english) routes

  get '', to: redirect("/#{I18n.locale}")

  # redsys MerchantURL 
  post '/orders/callback/redsys', to: 'orders#callback_redsys', as: 'orders_callback_redsys'

  namespace :api do
    scope :v1 do 
      scope :gcm do 
        post 'registrars', to: 'v1#gcm_registrate'
        delete 'registrars/:registrar_id', to: 'v1#gcm_unregister'
      end
      scope :user do
        get 'exists', to: 'v1#user_exists'
      end
    end
  end

  get '/favicon.ico', to: "organization#favicon"

  scope "/(:locale)", locale: /es|ca|eu/ do 

    devise_for :users, controllers: { 
      registrations: 'registrations', 
      passwords:     'passwords', 
      confirmations: 'confirmations'
    } 

    get '/privacy-policy', to: 'page#privacy_policy', as: 'page_privacy_policy'
    get '/preguntas-frecuentes', to: 'page#faq', as: 'faq'

    if Rails.application.secrets.features["notifications"]
      get :notices, to: 'notice#index', as: 'notices'
    end

    if Rails.application.secrets.features["openid"]
      get '/openid/discover', to: 'open_id#discover', as: "open_id_discover"
      get '/openid', to: 'open_id#index', as: "open_id_index"
      post '/openid', to: 'open_id#create', as: "open_id_create"
      get '/user/:id', to: 'open_id#user', as: "open_id_user"
      get '/user/xrds', to: 'open_id#xrds', as: "open_id_xrds"
    end

    if Rails.application.secrets.features["participation_teams"]
      get '/equipos-de-accion-participativa', to: 'participation_teams#index', as: 'participation_teams'
      put '/equipos-de-accion-participativa/entrar(/:team_id)', to: 'participation_teams#join', as: 'participation_teams_join'
      put '/equipos-de-accion-participativa/dejar(/:team_id)', to: 'participation_teams#leave', as: 'participation_teams_leave'
      patch '/equipos-de-accion-participativa/actualizar', to: 'participation_teams#update_user', as: 'participation_teams_update_user'
    end

    if Rails.application.secrets.features["proposals"]
      get '/propuestas', to: 'proposals#index', as: 'proposals'
      get '/propuestas/info', to: 'proposals#info', as: 'proposals_info'
      get '/propuestas/:id', to: 'proposals#show', as: 'proposal'
      post '/apoyar/:proposal_id', to: 'supports#create', as: 'proposal_supports'
    end

    if Rails.application.secrets.features["elections"]
      get '/vote/create/:election_id', to: 'vote#create', as: :create_vote
      get '/vote/create_token/:election_id', to: 'vote#create_token', as: :create_token_vote
      get '/vote/check/:election_id', to: 'vote#check', as: :check_vote
    end

    if Rails.application.secrets.features["verification_presencial"]
      scope '/verificadores' do 
        get '/', to: 'verification#step1', as: :verification_step1
        get '/nueva', to: 'verification#step2', as: :verification_step2
        get '/confirmar', to: 'verification#step3', as: :verification_step3
        post '/search', to: 'verification#search', as: :verification_search
        post '/confirm', to: 'verification#confirm', as: :verification_confirm
        get '/ok', to: 'verification#result_ok', as: :verification_result_ok
        get '/ko', to: 'verification#result_ko', as: :verification_result_ko
      end
      scope '/verificaciones' do 
        get '/', to: 'verification#show', as: :verification_show
      end
    end
    
    if Rails.application.secrets.features["microcredits"]
      get '/microcreditos', to: 'microcredit#index', as: 'microcredit'
      get '/microcréditos', to: redirect('/microcreditos')
      get '/microcreditos/provincias', to: 'microcredit#provinces'
      get '/microcreditos/municipios', to: 'microcredit#towns'
      get '/microcreditos/informacion', to: 'microcredit#info', as: 'microcredits_info'
      get '/microcreditos/:id', to: 'microcredit#new_loan', as: :new_microcredit_loan
      get '/microcreditos/:id/login', to: 'microcredit#login', as: :microcredit_login
      post '/microcreditos/:id', to: 'microcredit#create_loan', as: :create_microcredit_loan
    end
    
    authenticate :user do

      if Rails.application.secrets.features["verification_sms"]
        scope :validator do
          scope :sms do 
            get :step1, to: 'sms_validator#step1', as: 'sms_validator_step1'
            get :step2, to: 'sms_validator#step2', as: 'sms_validator_step2'
            get :step3, to: 'sms_validator#step3', as: 'sms_validator_step3'
            post :phone, to: 'sms_validator#phone', as: 'sms_validator_phone'
            post :captcha, to: 'sms_validator#captcha', as: 'sms_validator_captcha'
            post :valid, to: 'sms_validator#valid', as: 'sms_validator_valid'
          end
        end
      end
      
      if Rails.application.secrets.features["collaborations"]
        scope :colabora do
          delete 'baja', to: 'collaborations#destroy', as: 'destroy_collaboration'
          get 'ver', to: 'collaborations#edit', as: 'edit_collaboration'
          get '', to: 'collaborations#new', as: 'new_collaboration'
          get 'confirmar', to: 'collaborations#confirm', as: 'confirm_collaboration'
          post 'crear', to: 'collaborations#create', as: 'create_collaboration'
          post 'modificar', to: 'collaborations#modify', as: 'modify_collaboration'
          get 'OK', to: 'collaborations#OK', as: 'ok_collaboration'
          get 'KO', to: 'collaborations#KO', as: 'ko_collaboration'
        end
      end

      if Rails.application.secrets.features["blog"]
        scope :brujula do
          get '', to: 'blog#index', as: 'blog'
          get ':id', to: 'blog#post', as: 'post'
          get 'categoria/:id', to: 'blog#category', as: 'category'
        end
      end
    end

    # http://stackoverflow.com/a/8884605/319241 
    devise_scope :user do
      get '/registrations/regions/provinces', to: 'registrations#regions_provinces'
      get '/registrations/regions/municipies', to: 'registrations#regions_municipies'
      get '/registrations/vote/municipies', to: 'registrations#vote_municipies'

      authenticated :user do
        root 'tools#index', as: :authenticated_root
        get 'password/new', to: 'legacy_password#new', as: 'new_legacy_password'
        post 'password/update', to: 'legacy_password#update', as: 'update_legacy_password'
        delete 'password/recover', to: 'registrations#recover_and_logout'
      end
      unauthenticated do
        root 'devise/sessions#new', as: :root
      end
    end

    %w(404 422 500).each do |code|
      get code, to: 'errors#show', code: code
    end

    DynamicRouter.load
  end
  # /admin
  ActiveAdmin.routes(self)

  constraints CanAccessResque.new do
    mount Resque::Server.new, at: '/admin/resque', as: :resque
  end

  load "./vendor/overrides/#{Rails.application.secrets.organization["folder"]}/config/routes.rb"

end

app/models/participation_team.rb
class ParticipationTeam < ActiveRecord::Base
  has_and_belongs_to_many :user

	scope :active, -> { where(active: true)  }
end

app/controllers/participation_teams_controller.rb
class ParticipationTeamsController < InheritedResources::Base
  	before_action :authenticate_user!

	def index
  		@participation_teams = ParticipationTeam.active
  	end

	def join
		if params[:team_id]
			team = ParticipationTeam.find(params[:team_id])
			if team and not current_user.participation_team.member? team
				current_user.participation_team << team
				current_user.save
			end
		else
			current_user.update_attribute(:participation_team_at, DateTime.now)
			flash[:notice] = "Te damos la bienvienida a los Equipos de Acción Participativa. En los próximos días nos pondremos en contacto contigo."
		end			
		redirect_to participation_teams_path
	end

	def leave
		if params[:team_id]
			team = ParticipationTeam.find(params[:team_id])
			if team and current_user.participation_team.member? team
				current_user.participation_team.delete(team)
				current_user.save
			end
		else
			current_user.update_attribute(:participation_team_at, nil)
			flash[:notice] = "Te has dado de baja de los Equipos de Acción Participativa"
		end 
		redirect_to participation_teams_path
	end

	def update_user
		current_user.update_attribute :circle, params[:user][:circle]
		redirect_to participation_teams_path
	end
end

app/helpers/participation_teams_helper.rb
module ParticipationTeamsHelper
end

app/views/participation_teams/_wants_participation_buttons.html.erb
<% if current_user.participation_team_at.nil? %>
  <%= link_to "¡Únete!", participation_teams_join_path, class: "button", method: :put %>
<% else %>
  <%= link_to "Darme de baja", participation_teams_leave_path, class: "button button-danger", method: :put %>
<% end %>

app/views/participation_teams/index.html.erb
<% content_for :title, "Equipos de Acción Participativa" %>
<div class="content-content cols">
  <div class="row justify-texts">
    <div class="col-b-4a12">
      <%= content_tag(:h2, "Equipos de Acción Participativa") %>

  <% if !current_user.participation_team_at.nil? %>
     <p><a class="show_info" href="#">Mostrar más información sobre los Equipos de Acción Participativa</a> <a class="show_teams" href="#">Mostrar equipos temáticos</a>
      </p>
      <div id="participation_teams">
        <h3>Enlaces de Participación</h3>
        <p>Si indicas que participas en algún Círculo, contaremos contigo como enlace de participación de este, lo que nos permitirá informar y dinamizar en los círculos las iniciativas de participación que desarrollemos y asegurarnos de que exista una buena coordinación.</p>
        <%= semantic_form_for current_user, url: participation_teams_update_user_path do |f| %>
          <fieldset>
          <div class="inputlabel-box">
          <% if current_user.errors.include?(:circle) %>
            <%= field_notice_box %>
          <% end %>
          <%= f.input :circle, input_html: {autofocus: true, class: 'input-xl'} %>
          </div>
          </fieldset><%= f.action :submit, button_html: {class: "button"}  %>
        <% end %>

        <br/>
        <h2>Equipos temáticos</h2>
        <p>Ahora mismo estás adscrito/a a los Equipos de Acción Participa, que trabajarán en el territorio extendiendo la participación a la ciudadanía. <% if !@participation_teams.empty? %>De forma adicional tenéis la posibilidad de uniros a varios equipos temáticos como es, en este momento, el Equipo <%= @participation_teams[0].name %>.<% end %> Además es muy importante que indiquéis si estáis participando en algún Círculo, para contar con vosotros/as como posibles Enlaces de Participación en vuestro Círculo.</p>

      <% if @participation_teams.empty? %>
        <div class="team">
          <p>En este momento no hay equipos de participacion activos.</p> 
        </div>
      <% else %>
        <% @participation_teams.each do |participation_team| %>
          <div class="team">
            <h3><%= participation_team.name %></h3>
            <p><%= participation_team.description %></p>
            <% if current_user.in_participation_team? participation_team.id %>
              <%= link_to "Dejar", participation_teams_leave_path(team_id: participation_team.id), class: "button button-danger", method: :put %>
            <% else %>
              <%= link_to "Unirse", participation_teams_join_path(team_id: participation_team.id), class: "button", method: :put %>
            <% end %>
          </div>
        <% end %>
    <% end %>
    </div>
<% else %>

      <div class="buttonbox">
        <%= render partial: "wants_participation_buttons" %>
      </div>

<% end %>
      <div id="participation_teams_info">

        <br/>
        <br/>
          <%= content_tag(:h3, "Gente por el cambio") %>
          <p>Nos encontramos a un momento decisivo para cambiar el rumbo del contexto político de nuestro país. Para ello, frente a otros partidos que tienen un gran capital económico para invertir en campaña, nosotros y nosotras contamos con el apoyo y la ilusión de cientos de personas que quieren apoyar el proyecto. Para canalizar toda esta gente, se lanza “Gente por el cambio”, una iniciativa dirigida a todas aquellas personas que deseen formar parte activa de la campaña que Podemos realiza en las elecciones autonómicas. Gente por el Cambio es una manera de recoger y organizar la ilusión que ha despertado Podemos desde hace más de un año, en forma de pequeñas acciones y actividades que se van a llevar a cabo durante estas campañas autonómicas, y de cuyo éxito dependerá gran parte de nuestras posibilidades electorales. Tiene que ser una red abierta y dinámica, un lugar de encuentro, de acción y participación que resalte nuestro mayor valor: “somos gente corriente haciendo cosas extraordinarias”.</p>

          <p>Gente por el Cambio se vertebra a partir de toda la gente inscrita en los Equipos de Acción Participativa (EAPs). Gente por el Cambio es la primera fase de despliegue de estos EAPs, los cuales cumplirán funciones relacionadas directamente con las campañas electorales autonómicas. Dadas las grandes diferencias entre municipios y comunidades autónomas, estos equipos tendrán la tarea de adecuar las dinámicas de campañas a las especificidades locales, además de innovar con otras que piensen que puedan cumplir una función relevante en su territorio. Tener la oportunidad de compartir estas experiencias y replicar las que identifiquemos como las más destacadas puede activar un proceso de inteligencia colectiva que nos lleve a superar todas nuestras expectativas.</p>
          
          <p>Si quieres formar parte de esta campaña ¡Incorpórate a los Equipos de Acción Participativa y en breve nos pondremos en contacto contigo!</p>

          <p><%= link_to "Ver la Guía del Área de Participación", "http://podemos.info/guia-del-area-de-participacion/" %></p>

        <% if !current_user.participation_team_at.nil? %>
          <p><a class="show_teams" href="#">Mostrar equipos temáticos</a></p>
        <% end %>
      </div>

      <div class="buttonbox">
        <%= render partial: "wants_participation_buttons" %>
      </div>

    </div>
  </div>
</div>